Repository brizzai/auto-mcp, pull requests merged in 2025-05, with the labels that each got.

#1 🩹 Fix: Update README badge link and test function cleanup
  README.md
  internal/server/mcp_server_test.go
Labels: documentation, good first issue

#7 📝 Docs: Simplify README.md by adding CONFIGURATION.md
  .github/CONTRIBUTING.md
  README.md
  docs/CONFIGURATION.md
Labels: documentation

#14 🔥 Feature: Add Gitleaks Secret Scanning
  .github/workflows/pr-validation.yml
  .gitleaks.toml
  .pre-commit-config.yaml
Labels: enhancement

#12 🔥 Feature: Streamable HTTP and OAuth support
  .github/workflows/pr-validation.yml
  .pre-commit-config.yaml
  README.md
  cmd/auto-mcp/main.go
  config.yaml
  docs/CONFIGURATION.md
  docs/OAUTH.md
  examples/petshop/config/config.yaml
  go.mod
  go.sum
  internal/auth/constants/constants.go
  internal/auth/handlers/handlers.go
  internal/auth/middleware/middleware.go
  internal/auth/models/models.go
  internal/auth/oauth.go
  internal/auth/oauth_test.go
  internal/auth/providers/github.go
  internal/auth/providers/google.go
  internal/auth/providers/interface.go
  internal/config/config.go
  internal/server/handler/http.go
  internal/server/mcp_server.go
  internal/server/server.go
  internal/server/server_test.go
  internal/server/tool/handler.go
  internal/utils/response.go
Labels: enhancement
